AWSTemplateFormatVersion: "2010-09-09"
Description: S3 sample 

Parameters:
  NameBase:
    Description: this is base name.
    Type: String
    Default: sample01

Resources:
  TeradaS3ContentsBucket:          # S3バケットの設定
    Type: AWS::S3::Bucket
    Properties:
      AccelerateConfiguration: 
        AccelerationStatus: Enabled
      AccessControl: Private
      BucketName: !Sub s3contentsbucket-${NameBase}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256 
      VersioningConfiguration:
        Status: Enabled
      